services:
  backend:
    build: ./backend
    image: devopsregistrytp.azurecr.io/backend:latest  # <- Tag correcto para push
    container_name: backend
    ports:
      - "10000:10000"
    environment:
      - user=${db_user}
      - password=${db_password}
      - host=${db_host}
      - port=${db_port}
      - dbname=${db_name}

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
    image: devopsregistrytp.azurecr.io/frontend:latest  # <- Tag correcto para push
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
