version: "3.9"

services:
  redis:
    image: redis:latest # o devopsregistrytp.azurecr.io/redis:latest si la subiste a ACR
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD} # solo si querés autenticación local

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "10000:10000"
    depends_on:
      - redis
    environment:
      # Postgres (supabase)
      - user=${DB_USER}
      - password=${DB_PASSWORD}
      - host=${DB_HOST}
      - port=${DB_PORT}
      - dbname=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
