name: Build, Push and Deploy to Azure

on:
  push:
    branches: ["docker"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login en ACR
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: devopsregistrytp.azurecr.io
          username: devopsregistrytp
          password: R4vrzbA7fAuzv8L1jcFqIEorWmW/DnPUEh2bzet+95+ACRDKleJv

      # Build & push imágenes
      - name: Build and Push Backend
        run: |
          docker build -t devopsregistrytp.azurecr.io/backend:latest ./backend
          docker push devopsregistrytp.azurecr.io/backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t devopsregistrytp.azurecr.io/frontend:latest ./frontend
          docker push devopsregistrytp.azurecr.io/frontend:latest

      # Login en Azure con usuario/contraseña
      - name: Azure CLI login
        run: |
          az login -u "${{ secrets.AZURE_USERNAME }}" -p "${{ secrets.AZURE_PASSWORD }}"

      # Deploy Backend
      - name: Deploy Backend Container
        run: |
          az container delete --resource-group tp-devops --name backend --yes || true
          az container create \
            --resource-group tp-devops \
            --name backend \
            --image devopsregistrytp.azurecr.io/backend:latest \
            --cpu 1 --memory 1 \
            --ports 10000 \
            --environment-variables \
              POSTGRES_USER=${{ secrets.DB_USER }} \
              POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
              POSTGRES_HOST=${{ secrets.DB_HOST }} \
              POSTGRES_PORT=${{ secrets.DB_PORT }} \
              POSTGRES_DB=${{ secrets.DB_NAME }} \
              REDIS_HOST=redis-17428.c56.east-us.azure.redns.redis-cloud.com \
              REDIS_PORT=17428

      # Deploy Frontend
      - name: Deploy Frontend Container
        run: |
          az container delete --resource-group tp-devops --name frontend --yes || true
          az container create \
            --resource-group tp-devops \
            --name frontend \
            --image devopsregistrytp.azurecr.io/frontend:latest \
            --cpu 1 --memory 1 \
            --ports 3000 \
            --environment-variables \
              NEXT_PUBLIC_API_URL=http://20.120.45.12:10000 \
              NEXT_PUBLIC_SUPABASE_URL=https://illglqdcmfjqktkyxhhh.supabase.co \
              NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_GvcxsZEZvkvsrDj6qhlbkw_2Gb8sFF6
