name: Build, Push and Deploy to Azure

on:
  push:
    branches: ["docker"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login en ACR (para docker build/push)
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: devopsregistrytp.azurecr.io
          username: devopsregistrytp
          password: R4vrzbA7fAuzv8L1jcFqIEorWmW/DnPUEh2bzet+95+ACRDKleJv

      # Login a Azure con el SP
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "9f50ed35-218d-4af0-922f-12bde1825ef7",
              "clientSecret": "UOU8Q~UUxDOOP49NtOsQyCmKpSR.L~j4_tUW8cIG",
              "subscriptionId": "811d5445-f311-40c1-be02-5f92a5819ee2",
              "tenantId": "35e9cd03-43d0-4947-b582-a6965c4cb674",
              "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
              "resourceManagerEndpointUrl": "https://management.azure.com/",
              "activeDirectoryGraphResourceId": "https://graph.windows.net/",
              "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
              "galleryEndpointUrl": "https://gallery.azure.com/",
              "managementEndpointUrl": "https://management.core.windows.net/"
            }

      - name: Export environment variables
        run: |
          echo "db_user=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "db_password=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "db_host=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "db_port=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "db_name=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "REDIS_HOST=redis-17428.c56.east-us.azure.redns.redis-cloud.com" >> $GITHUB_ENV
          echo "REDIS_PORT=17428" >> $GITHUB_ENV
          echo "REDIS_PASSWORD=iqaLW1kalNrUmpx7LdlQA0RQ1bVpIeYe" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SUPABASE_URL=https://illglqdcmfjqktkyxhhh.supabase.co" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_GvcxsZEZvkvsrDj6qhlbkw_2Gb8sFF6" >> $GITHUB_ENV

      - name: Build & Push Backend image
        run: |
          docker build -t devopsregistrytp.azurecr.io/backend:latest ./backend
          docker push devopsregistrytp.azurecr.io/backend:latest

      - name: Deploy Backend
        run: |
          az container delete --resource-group tp-devops --name backend --yes || true
          az container create \
            --resource-group tp-devops \
            --name backend \
            --image devopsregistrytp.azurecr.io/backend:latest \
            --cpu 1 --memory 1 \
            --os-type Linux \
            --ports 10000 \
            --ip-address public \
            --registry-login-server devopsregistrytp.azurecr.io \
            --registry-username devopsregistrytp \
            --registry-password R4vrzbA7fAuzv8L1jcFqIEorWmW/DnPUEh2bzet+95+ACRDKleJv \
            --restart always \
            --environment-variables \
              user=${db_user} \
              password=${db_password} \
              host=${db_host} \
              port=${db_port} \
              dbname=${db_name} \
              REDIS_HOST=${REDIS_HOST} \
              REDIS_PORT=${REDIS_PORT} \
              REDIS_PASSWORD=${REDIS_PASSWORD}

      - name: Get Backend Public IP
        id: get-backend-ip
        run: |
          BACKEND_IP=$(az container show \
            --resource-group tp-devops \
            --name backend \
            --query ipAddress.ip \
            -o tsv)
          echo "BACKEND_IP=$BACKEND_IP" >> $GITHUB_ENV
          echo "Backend levantado en: http://$BACKEND_IP:10000"

      - name: Build & Push Frontend image with build args
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=http://${BACKEND_IP}:10000/ \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
            --build-arg NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY} \
            -t devopsregistrytp.azurecr.io/frontend:latest ./frontend

          docker push devopsregistrytp.azurecr.io/frontend:latest

      - name: Deploy Frontend
        run: |
          az container delete --resource-group tp-devops --name frontend --yes || true
          az container create \
            --resource-group tp-devops \
            --name frontend \
            --image devopsregistrytp.azurecr.io/frontend:latest \
            --cpu 1 --memory 1 \
            --os-type Linux \
            --ports 3000 \
            --ip-address public \
            --registry-login-server devopsregistrytp.azurecr.io \
            --registry-username devopsregistrytp \
            --registry-password R4vrzbA7fAuzv8L1jcFqIEorWmW/DnPUEh2bzet+95+ACRDKleJv \
            --restart always \
            --environment-variables \
              NEXT_PUBLIC_API_URL=http://${BACKEND_IP}:10000/ \
              NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
              NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
